"""empty message

Revision ID: 0d125ea4d38e
Revises: 3d160b2fa188
Create Date: 2022-08-16 04:32:28.788434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d125ea4d38e'
down_revision = '3d160b2fa188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artist', 'phone',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.BIGINT(),
               postgresql_using= 'phone::bigint',
               existing_nullable=False)
    op.alter_column('show', 'start_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.DateTime(),
               postgresql_using= 'start_time::timestamp without time zone',
               existing_nullable=False)
    op.alter_column('venue', 'phone',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.BIGINT(),
               postgresql_using= 'phone::bigint',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'phone',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('show', 'start_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('artist', 'phone',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
